USE [master]
GO

/****** Object:  Database [MarathonSkills]    Script Date: 27.02.2025 15:53:23 ******/
CREATE DATABASE [MarathonSkills]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MarathonSkills', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MarathonSkills.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MarathonSkills_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MarathonSkills_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MarathonSkills].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MarathonSkills] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MarathonSkills] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MarathonSkills] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MarathonSkills] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MarathonSkills] SET ARITHABORT OFF 
GO

ALTER DATABASE [MarathonSkills] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MarathonSkills] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MarathonSkills] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MarathonSkills] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MarathonSkills] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MarathonSkills] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MarathonSkills] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MarathonSkills] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MarathonSkills] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MarathonSkills] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MarathonSkills] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MarathonSkills] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MarathonSkills] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MarathonSkills] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MarathonSkills] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MarathonSkills] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MarathonSkills] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MarathonSkills] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MarathonSkills] SET  MULTI_USER 
GO

ALTER DATABASE [MarathonSkills] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MarathonSkills] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MarathonSkills] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MarathonSkills] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MarathonSkills] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MarathonSkills] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MarathonSkills] SET  READ_WRITE 
GO

